# Generated by Django 3.0.8 on 2020-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackgroundPredictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputimage',
            name='foreground_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inputimage',
            name='output_trimap',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
